Unbeatable computer
solidlikeplato/tic-tac-toe-java pull request #13
Opened 2020-03-18 15:26 UTC by solidlikeplato

2020-03-20 18:21 UTC, solidlikeplato commented on src/main/java/tic/tac/toe/UnbeatableComputer.java
> +    int findWin(Board board, char symbolToCheck) {
make explicit that functions are private

2020-03-20 18:22 UTC, ericmeyer requested changes

2020-03-20 18:22 UTC, ericmeyer commented on src/main/java/tic/tac/toe/Board.java
> +            .map(cell -> getMarkAt(cell))
I'm not positive, but I think you can do something like this:
```suggestion
            .map(this::getMarkAt)
```

2020-03-20 18:22 UTC, ericmeyer commented on src/main/java/tic/tac/toe/Board.java
> +    List<Character> cells = Arrays.stream(cellsToGet)
```suggestion
    return Arrays.stream(cellsToGet)
```

2020-03-20 18:22 UTC, ericmeyer commented on src/test/java/tic/tac/toe/MenuTest.java
> -    public void menuTellsPlayerInvalidInputFor3Players() {
What caused this test to be removed?

2020-04-02 19:01 UTC, ericmeyer requested changes

2020-04-02 19:01 UTC, ericmeyer commented on src/main/java/tic/tac/toe/Game.java
> +  public static final int[][] WINNING_COMBINATIONS = new int[][]{{1, 4, 7}, {2, 5, 8}, {3, 6, 9}, {1, 2, 3}, {4, 5, 6}, {7, 8, 9}, {1, 5, 9}, {3, 5, 7}};
If you recall, knowledge duplication between the `ComputerPlayer` and the `Game` was the original impetus to introduce the `Rules` class. Is there a way to leverage the `Rules` class you introduced to reduce the amount of complexity in `Game`?

2020-04-02 19:01 UTC, ericmeyer commented on src/test/java/tic/tac/toe/RulesTest.java
> +/*
Can these comments be removed at this point?

2020-04-02 19:01 UTC, ericmeyer commented on src/test/java/tic/tac/toe/RulesTest.java
> +public class RulesTest {
I would have expected more tests of this class. Ideally, this class would have been fully test-driven before updating the `ComputerPlayer` to use it.

For example, I would have expected tests for winning in a row, a column, a diagonal, etc.

2020-04-06 18:46 UTC, ericmeyer approved these changes

2020-04-07 00:24 UTC, merged